import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import WebGLCanvas from "./components/webGL/WebGLCanvas";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="fixed inset-0 z-0" style={{ isolation: 'isolate' }}>
          <WebGLCanvas />
        </div>
        <div className="fixed inset-0 z-5 blur-overlay" style={{ isolation: 'isolate', pointerEvents: 'none' }}>
        </div>
        <div className="relative z-10" style={{ isolation: 'isolate' }}>
          {children}
        </div>
      </body>
    </html>
  );
}
