import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import CampScene from "./components/CampScene";
import IdleWrapper from "./components/IdleWrapper";
import Header from "./components/Header";
import { AuthProvider } from "./components/auth/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const kanit = localFont({
  src: [
    {
      path: "../public/fonts/Kanit/Kanit-Thin.ttf",
      weight: "100",
      style: "normal",
    },
    {
      path: "../public/fonts/Kanit/Kanit-ThinItalic.ttf",
      weight: "100",
      style: "italic",
    },
    {
      path: "../public/fonts/Kanit/Kanit-ExtraLight.ttf",
      weight: "200",
      style: "normal",
    },
    {
      path: "../public/fonts/Kanit/Kanit-ExtraLightItalic.ttf",
      weight: "200",
      style: "italic",
    },
    {
      path: "../public/fonts/Kanit/Kanit-Light.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/fonts/Kanit/Kanit-LightItalic.ttf",
      weight: "300",
      style: "italic",
    },
    {
      path: "../public/fonts/Kanit/Kanit-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/Kanit/Kanit-Italic.ttf",
      weight: "400",
      style: "italic",
    },
    {
      path: "../public/fonts/Kanit/Kanit-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/Kanit/Kanit-MediumItalic.ttf",
      weight: "500",
      style: "italic",
    },
    {
      path: "../public/fonts/Kanit/Kanit-SemiBold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../public/fonts/Kanit/Kanit-SemiBoldItalic.ttf",
      weight: "600",
      style: "italic",
    },
    {
      path: "../public/fonts/Kanit/Kanit-Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../public/fonts/Kanit/Kanit-BoldItalic.ttf",
      weight: "700",
      style: "italic",
    },
    {
      path: "../public/fonts/Kanit/Kanit-ExtraBold.ttf",
      weight: "800",
      style: "normal",
    },
    {
      path: "../public/fonts/Kanit/Kanit-ExtraBoldItalic.ttf",
      weight: "800",
      style: "italic",
    },
    {
      path: "../public/fonts/Kanit/Kanit-Black.ttf",
      weight: "900",
      style: "normal",
    },
    {
      path: "../public/fonts/Kanit/Kanit-BlackItalic.ttf",
      weight: "900",
      style: "italic",
    },
  ],
  variable: "--font-kanit",
  display: "swap",
  fallback: ["system-ui", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "Helvetica Neue", "Arial", "sans-serif"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=Kanit:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Kedebideri:wght@400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} ${kanit.variable}`}>
        <AuthProvider>
          <div className="fixed inset-0 z-0 w-screen h-screen">
            <CampScene />
          </div>
          <IdleWrapper idleTimeoutSeconds={30}>
            <Header />
            <div className="relative z-10">{children}</div>
          </IdleWrapper>
        </AuthProvider>
      </body>
    </html>
  );
}